#+TITLE: Oh My Soundness
#+date: <2022-09-20 03:39>
#+description: Soundness, Completeness, Recall, Precision, Static and Dynamic Analyses
#+filetags: program-analysis notes static-analysis dynamic-analysis blog 

#+HTML_HEAD: <link rel="stylesheet" href="https://dynaroars.github.io/files/org.css">

Our [[https://dynaroars.github.io/][Dynaroars]] group (Didier, Hai, Linhan, and Vu) [[https://github.com/dynaroars/dynaroars.github.io/wiki/Weekly-Meetings][recently]] read Mike Hick's post on [[http://www.pl-enthusiast.net/2017/10/23/what-is-soundness-in-static-analysis/][soundness in static analysis]].  It was a really good read as Mike made it easy to follow and understand these common, yet confusing definitions and terminologies.  We also had a good discussion on how these definitions from static analysis would apply to dynamic analysis (e.g., testing). Below is our summarization.

* Summarization of Mike's post

** Mathematical Logic

First is the definitions of soudness and completeness of from mathematical logic.  These properties are applied to a proof system ~T~, which takes in a statement (i.e., a logical formula) ~s~ and either proves or disproves that statement. 

- soundness (~T~ is sound):: if ~T~ provides a proof of ~s~, then ~s~ is indeed true.
- completeness (~T~ is complete):: if ~s~ is true, then ~T~ provides a proof for ~s~.

In other words, ~T~ is sound if things that it proves are indeed true (equivalently, if ~T~ only proves true things), and that ~T~ is complete if it can prove any true statements.

*Thoughts*: Intuitively we can see that being *sound* (my proofs are correct) seems easier to achieve than being *complete* (I can prove any things that are true, e.g., I can give a statement representing Fermat's last theorem and expect the machine to throw out a complete proof)[fn:1].  Of course we know by now it is /possible/ to have a proof system that is both sound and complete for proposition logic (Completeness Theorem) but it is not possible to have such a system in first-order logic (Incompleteness theorem).



** Static Analysis

Now let's adapt these definitions to static analysis. Let's assume we want to use a static verifier ~T~ to check if a program ~S~ has some desirable property ~R~ (e.g., does not have division by 0). 
For simplicity, we assume ~T~ either =proves= or =disproves= that ~S~ has ~R~ (in practice, most tools also return =unknown= indicating ~T~ cannot handle the ~S~ or ~R~ or times out). Morover, when ~T~ disproves that ~S~ has ~R~, it also returns a counterexample (=cex=), which typically is an input causing ~S~ to violate ~R~ (causing ~S~ to perform a div-by-0 operation).

- soundness (~T~ is sound) :: *if* ~T~ proves that a ~S~ has ~R~, *then* ~S~ has ~R~.

  For example, if the verifier says the program is safe of div-by-0 error, then the program trully does not have that error.)

- completeness (~T~ is complete) :: *if* ~S~ has ~R~, *then* ~T~ proves that ~S~ has ~R~.

  For example, if the program is safe of div-by-0 error, then ~T~ proves that.

*Thoughts*: We often talk about how algorithms and tools often sacrifice completeness for soundness, so let's define unsound and incomplete properties. We can do this by just negating the definitions of soundness of completeness above.

- unsound :: ~T~ proves that a ~S~ has ~R~ *but* ~S~ /does not/ has ~R~.

  For example, the verifier proves the program is safe of div-by-0 error, but the program has that error.

- incomplete ::   ~S~  has ~R~ but ~T~ disproves that ~S~ has ~R~.

  For example, the program is safe of  div-by-0 error,  ~T~ says that it has that error (and provides a counterexample for that).

  So on one hand, unsound gives us a false confidence that our program is safe or has some desirable property while it does not. On the other hand, soundness gives us a false warning (and spurious counterexample) claiming our program is unsafe or does not satisfy some property while it does. 




*** Soundiness

Achieving both soundness and completeness is usually not possible. Requiring just one of them might not mean much, e.g., a  tool that never proves anything is always sound and a tool that disproves everything is always complete. In general we want soundness, but not the kind of soundness that never proves anything. 


- soundiness :: 

Finally, =precision= and =recall= can be used as a metrics for soundness and completeness.  Let $N$ be the set of programs we want to analyze using a static tool, $X \subseteq N$ the set of programs that have the property of interest, $N-X$ the set of programs that do not have the proeprty of interst.  Moreover, let $T \subseteq X$ be the set of programs that are (correctly) proved by the tool, and $F \subseteq (N - X)$ the set of programs that are (incorrectly) proved the the tool.  Then,

The static analysis's =precision= and =recall= are

- precision :: $\frac{|T|}{|T| + |F|}$


* Extension to Dynamic Analysis

  Mike's post focuses on static analysis analysis (e.g., a verification
  tool).  Does it then apply to dynamic analysis (e.g., a testing tool)?
  We often hear that static and dynamic analyses compliment one another,
  e.g., /verification proves the absense of error while testing proves
  the existence (through valid counterexamples)/.  Moreover, we hear that
  static approaches aim to be sound, but not complete, then does that
  mean dynamic and testing techniques aim for completeness but not
  sound? How is being complete related to not producing spurious counterexamples and all that?

At first glance, it seems the definition of completeness above (if a program has a property then the tool can prove that) does not apply to the ability to find bugs and not producing spurious counterexamples. However, it does as shown below.

The completeness definition above says that  "*if* ~S~ has ~R~, *then* ~T~ proves that ~S~ has ~R~".
Let ~S~ has ~R~ be represented by a statement ~A~ and ~T~ proves that ~S~ has ~R~ represented by a statement ~B~. Then we have 

#+begin_src 
A => B # completeness
= !A V B  
= B V !A
= !B => !A
#+end_src

Thus we have an equivalent definition for completeness of static analysis that makes sense for testing

- completeness :: *if* ~T~ disproves that ~S~ has ~R~ *then* ~S~ does not have ~R~.

In other words, if a testing tool finds an input to a program that violate the property, then that really means the property is not valid in the program. This makes sense for dynamic analysis and testing because indeed we expect that when a testing tool finds a violation, it is actually a violation (because testing actually runs the program and thus can observe that bugs actually occured).

Similarly, we do the same for soundness

#+begin_src 
B => A # soundness
= !B V A  
= A V !B
= !A => !B
#+end_src

- soundness :: *if*  ~S~ does not have ~R~ *then* ~T~ disproves that ~S~ has ~R~.


So this means that dynamic analysis and testing are indeed complete ().

* Footnotes

[fn:1]


For example, we should be able to trust when a verify says the program is safe, cannot trust if it says the program is unsafe because its counterexamples can be spurious. On the other hand, we can trust a testing tool when it presents a counterexample showing the program is unsafe (because it actually runs the program on that input and observes a property violation), but we cannot trust if a testing tool says the program has no error (because it only tests the program on some finite set of inputs).

this mean that verification tools aim for soundness testing tools aim for completeness ?  Do the definitions of completeness for static analysis apply to a bug-finding testing tool? 
