#+TITLE: 3200 W Buckthorn
#+date: <2021-07-3 03:39>
#+description: how I set up my CV
#+filetags: TeX cv blog 


* [[https://photos.app.goo.gl/4c2wpUNMpk918sfD7][PICTURES]]
  
** Brief history
   - Bought this acreage in December 2016.
   - our first house, we have no itention of getting an acreage (in fact, we don't even know what an acreage is),  but we just fell in love with it and decide to go for it. Best decision ever!
   - As it turns out, living in an acreage is a wonderful experience and the best part is that taking care of it is much easier than we thought.

** Mowing
  - About 3 hrs to mow the grass.
  - mowing is a fun and relaxing activity that my wife and I would argue on who gets to mow the grass and who has to watch the kids.
  - Whenever I need to take a break from work, I would go mow the grass ... it is simply fun and easy.
  - Tip:  get a good mower;  we got a John Deere zero turner with 60"---it is both easy to use and to maintain.  

** Snowing
  - When first move here, were worrying that snowing would be bad because the city would not come down here quick enough as it is a rural area.  
  - After 5 years of living here we actually still don't know (and don't care) if the city would come early or not  
       - Right after a big snow the neighbors would come down with heavy equipments and tractors and just clean up the whole neighborhood. 


** Orchard
  - 25 or so apple and pear trees of various types (probably 10 types of apples).  
  - John, the previous owner, used to sell apples at farmer market.  
  - Maintain an orachard takes lots of time, but enjoyable and rewarding as the apples are quite fruitful (each tree probably gives hundreds of apples during its season (so we have thousand of apples and pears).  
  - (see pictures from Google Photos link above)

- Tip: if you don't want to take care of these apple trees, you can just let them grow or cut some of them down.  


** Appliances
  - Already have an outstanding Bosch dishwasher last year
  - Our old ones are really old, so decide to replace new ones 
  - Hard to get appliances (especially fridge) due to space limitation
    - so either remodel the whole kitchen (which of course would cost a lot)
    - or pay extra to get the right-size appliances (what we did)
  - went for those that both loook nice, match the Bosch's black stainless steel, and reliable (based on reviews), so spent on appliances quite a bit.  
 - At the end kitchen looks a lot better (and we don't think the new owner can complain about these appliances, i.e., unlikely they can find something better that would fit).


** Neighbor 
   - exceptionally awesome neighbor 
   - help burn trees and other yard tasks
   - help cut trees
   - help clean snow 
   - (see pictures from Google Photos link above)
     
