#+TITLE: My Website and Blog  Setup
#+date: <2021-06-05 03:39>
#+description: how I set up my website
#+filetags: computer setup blog

#+HTML_HEAD: <link rel="stylesheet" href="https://dynaroars.github.io/files/org.css">


Minimal CSS that automatically switches btw light and dark, and blog setup using ~org-static-blog~

* Auto Dark/Light Scheme Change

  My website automatically changes its color to dark and light setting depending on the user's OS preference. This useful custmization is quite simple with CSS using the ~@media (prefers-color-scheme: dark) {...}~ feature.  Below is a minimal CSS example that lists light (default) and dark color schemes and automatically changes to the preferred one set by your OS or Window Manger.

  #+begin_src css
    body {
        background: #f6f6f6;
    }

    @media (prefers-color-scheme: dark) {
        body {
            color: lightgray;
            background: #454545;
        }
    }

  #+end_src


  Here's the actual [[https://dynaorars.github.io/files/org.css][CSS]] file I use for my website.
  #+INCLUDE: "../../../dynaroars/docs/files/org.css" src css

* Using [[https://github.com/bastibe/org-static-blog][org-static-blog]]

  I use =Org Mode= in Emacs for my website and =org-static-blog= for [[./index.html][my blog]].

  - Below shows the setup for my blog, which has the following hierachy:
    - =org/= :  store =.org= source files
    - =posts/= : store output =.html= files
    - =files/= : store miscellaneous files (e.g., pictures) used by my blog entries
      - =header.html=
        #+INCLUDE: "../files/header.html" src html
      - =preamble.html=
        #+INCLUDE: "../files/preamble.html" src html  
      - =postamble.html=
        #+INCLUDE: "../files/postamble.html" src html
        
  - =.emacs= setup
    #+begin_src lisp
      (use-package org-static-blog
        :ensure t
        :config
        (setq
         org-static-blog-publish-title "ThanhVu's website"
         org-static-blog-publish-url "./"
         org-static-blog-publish-directory "/Users/tnguyen/git/www/nguyenthanhvuh/docs/posts/"
         org-static-blog-posts-directory "/Users/tnguyen/git/www/nguyenthanhvuh/docs/org/"
         org-static-blog-drafts-directory "/Users/tnguyen/git/www/nguyenthanhvuh/docs/drafts/"
         org-static-blog-use-preview t
         org-static-blog-preview-convert-titles t
         org-static-blog-preview-ellipsis "..."   
         org-static-blog-enable-tags t
         org-static-blog-index-length 10
         org-export-with-toc t
         org-export-with-section-numbers t

         org-static-blog-page-header (with-temp-buffer
                                       (insert-file-contents
                                        "/Users/tnguyen/git/www/nguyenthanhvuh/docs/files/header.html")
                                       (buffer-string))

         org-static-blog-page-preamble (with-temp-buffer
                                         (insert-file-contents
                                          "/Users/tnguyen/git/www/nguyenthanhvuh/docs/files/preamble.html")
                                         (buffer-string))

         org-static-blog-page-postamble (with-temp-buffer
                                          (insert-file-contents
                                           "/Users/tnguyen/git/www/nguyenthanhvuh/docs/files/postamble.html")
                                          (buffer-string))

         org-static-blog-index-front-matter "<h1> ThanhVu's blog </h1>\n")
        )

    #+end_src

  

