#+TITLE: LaTeX Letterhead 
#+date: <2021-08-26 02:58>
#+description: letter head
#+filetags: TeX letter 


My answers to https://www.cs.columbia.edu/wp-content/uploads/2019/03/Get-Advisor.pdf

** Advisor Style & Expectations
1. Does the professor have tenure yet? [engagement level, PhD might get interrupted]
   A: No, not yet. I am applying for tenure this semester in Spring'23.

   It is worth noting that when I moved from UNL to GMU in 2021, all but 1 of my students who was graduating the next semester came with me.
   
1. What is the professor’s formal training / background / PhD? [helps contextualize problems/approaches]
   A: I did my Ph.D. in CS in the University of New Mexico-Albuquerque.  I started wanting to work on evolutionary computing, and then gradually changed to software engineering and programming languages.
   
1. What have previous lab members done after getting their PhD? [Gone to industry?/Post-doc?/Professor?]
   
1. What is the lab structure? [how collaborative/disjointed are lab members' projects?]

   
1. Does the advisor consider themselves a ‘hands-on’ or ‘hands-off’ advisor?
1. How does the advisor give feedback on papers/what is their feedback style?
1. How often does the advisor meet with their students? [1:1 or all together? Daily guidance by PI or post-doc?]
1. Are there lab meetings? What are other meetings you will see your advisor in a group with other people?
1. What does a group/lab meeting look like? [Or other relevant meetings]
1. How many students are in the group? [Number of undergrad/masters/phd/post doc]
1. What progress does the advisor generally expect from a student in the course of a semester? [Submission/Publication pace]
1. What other expectations does the advisor have for their students: time/vacation/paper/project/experiment wise etc.
◻
“When have you given a letter of concern? Why?”
◻
“What do you do when students are struggling”?

Research Fit & Projects

    How directly applicable will your future technical skills be to the roles you want after graduating. (If set on industry)

    A: Most of the future technical skills in computer vision and machine learning will apply to many (either research or engineering) roles in the industry.

    What’ research methods’ does the lab use? (What ‘types’ of papers / contributions / conferences targeted)

    A: Our work is often empirically driven and focuses on developing robust algorithms that work under unconstrained environments (e.g., everyday photos/videos). Target conferences are Vision CVPR/ICCV/ECCV; Graphics: SIGGRAPH/SIGGRAPH Asia; Learning: ICLR/NeurIPS. For work we wish to extend, we also publish in journals such as IEEE T-PAMI / IJCV.

    “What are some of the projects that you and your students are currently working on”?

    A: We are working on various computational photography projects, including view synthesis, 3D photos/videos, and generative models for controllable image/video synthesis. We are also interested in tackling challenging problems with positive societal impacts.

    “In general, do you tend to give your students projects or have them select their own”?

    A: It depends. I prefer students to develop and pursue their ideas. My research agenda is my students’ agenda. However, this could be challenging for junior students. For junior students, I constrain the project scope a bit so they can focus on developing their core research skills.

    “Do you have particular projects that you see me working on”?

    A: It depends on your background and interests.

    “How much freedom do you think I'd have in selecting my own projects”?

    A: We need to brainstorm to find projects or research directions that we are both passionate about. For example, if you select a project that is entirely outside my expertise, I will need more support to provide the support you need. If that's the case, we can discuss several options, such as switching to a different advisor or finding another faculty with the relevant expertise to co-advise your projects.

    “Are there other students you are interested in working with? If so, what would they be working on project-wise”?

    A: I will be able to answer this after reviewing the pool of applicants.

    “Would they have their own line of work or contribute to a bigger project/someone else's project”?

    A: It's up to you. Leading a project yourself is the best way to get you started for learning how to do research. Usually a, student has their line of work and 1-2 projects where they collaborate with/support others.


Student-Advisor Fit / Placement

    [If you are interested] Would the advisor be interested in co-advising?

    A: Of course! If co-advising helps your research, why not? Let me know if you find another faculty within UMD with the expertise that can help with your work. Even faculty/researchers outside UMD would work as well. We can reach out and see if there are opportunities for collaboration.

    “Are you taking a student” /“Do you have funding to take students in this year (or, for which projects)”

    A: We always are looking for new students each year. Our lab is growing. I plan to recruit 2-4 Ph.D. students starting in Fall 2023.

    “What factors will affect whether or not you take a student”?

    A: Research interests, background, and motivation.

    “How do you anticipate your funding to change during my time as a student”?

    A: I do not anticipate any changes. Your time as a student will be fully funded either by a research or a teaching assistantship.

    “Do you think our research interests are a good match”?

    A: Let me know what you like to work on.

    “Are there other students in my cohort that you're interested in working with”? (If so, are you taking more than one student?)

    A: Not yet. I plan to recruit 2-4 Ph.D. students this year.

    “I'm interested in working with you. Do you think I'd have a good chance of working with you if I come to your university”?

    A: I would be more than happy to chat! If you come, we can work on a small-scale project and see if this is what you are looking for. In the meantime, feel free to reach out to other faculty and explore different opportunities.

    “Are there other faculty you think I'd be a good match for”?

    A: Yes! Check out the list of faculty members grouped by area. Here are a couple of areas that overlap with mine.

        Computer Vision and Machine Perception,

        Machine Learning and Data Science,

        Graphics Visualization and VR AR,

        AI and Robotics,

        Natural Language Processing.

** Funding / Obligations
◻1. Where does their funding primarily come from? [If military / industry-focused funding bothers you, figure this out]
1. What are their constraints from their funding source? [Some restrict research topic and change final deliverables. Some add
work — writing progress reports, traveling, preparing presentations for the funding source or engineering overhead for
integration]
1. If your advisor made you work on a project in their area that you are least interested in (e.g. for a grant) would you still be
excited doing that work? [Useful for choosing between advisors]
◻
“If you run out of your primary funding for a student how do you expect the student to handle that” [advisor’s responsibility /
you’ll have to write a grant with me / dept will cover the student / you have to find their own funding]
◻
“What does the quals process look like”?
◻
“Is there a TA requirement”? / “How often would I be expected to TA”?

** Co-advising
1. How much overlap would they have in research?
1. Have these advisors co-advised in the past? Or worked together in the past?

** Lab Culture
◻1. How often do grad students get to attend conferences? [Pace + What constraints]
◻1. Do students mostly work with senior students or directly with professor?
◻1. How many conferences are students expected to target a year? [remember pubs ≠ submissions]
◻◻1. How often do students take time off? Are there lab / department outings/events?
1. Are there snacks in the lab?
◻1. Is the professor in an 80/20 with a company? Are student’s research projects tied to industry funding?
◻◻◻1. Will it be acceptable/encouraged to intern at a company during the summer? [Does this change with seniority?]
◻◻1. Do students work together in common space? Is their common space? Do students often get meals together?
◻◻1. Do students often work late? [Often / only before conference deadlines.]
◻1. How often are students expected to be contactable by their advisor. [Email, slack, hangouts. Online around the cl

#+INCLUDE: "~/git/projects/letterhead/ref-letter.tex" src latex
