#+title: Applying to Grad School
#+date: <2021-07-05 14:33>
#+description: 
#+filetags: students research
#+OPTIONS: ^:nil toc:nil num:nil

#+HTML_HEAD: <link rel="stylesheet" href="https://dynaroars.github.io/files/org.css">

I've been in the Ph.D. admission committee for the past 7 years and have read and discuss many applications. So I thought it might be useful to share my thoughts about how to write an good application. My aim is to help *international students*, in particular *Vietnamese students*, who might not be too familiar with the CS grad school admission process in the US. Of course, this goes without saying that these are just my personal opinion and experience and so they might or might not apply in your case.


** Do I really have a chance to apply to a Ph.D. program in the US?
- short answer: *yes, you do*!
- If you plan to apply Ph.D. programs at other countries (e.g., Singapore, Australia) then there is no reason to not try your chance at a U.S. universities.

** Why I get rejected? (why do Vietnamese applications often get rejected from US universities?)
- Reason 1: US profs. do not know well about schools in Vietnam.
  - They treat Bach Khoa or other top Vietnamese university as just unknown/unfamiliar foreign universities.  This is not just Vietnamese schools, but schools in other countries too. There are just simply too many schools and we simply can't know all of them except may be the top 100 ones (and unfortunately Bach Khoa is not the top 100).
  - *Solution*: It helps if you explicitly state your university is the top in your statement.  It also helps a lot if there is a Vietnamese in the faculty who can tell them the top universities in VN.  

- Reason 2: your writing is poor
  - Understandably, Vietnamese students do not write good English.  You are also not used to the English writing style, e.g., too short, too verbose, too formal, too informal.  So if we can't understand your writing, don't feel exciting or convinced, then your application won't get far.
  - *Solution*: get someone who has experiences with writing statement to help. 

    

** Should I contact a professor before?
- short answer: *If you seriously want to work with that professor, then yes, you should*.
- To be effective, you need to do your homework about the work of that professor, shows them that you know about their work (e.g., read a couple of their papers, talk about it)
- Also say why your experience and background make you a good candidate for those research.
- If you cannot customize your email as such, then don't waste your time.  We will likely just skim over your message and probably won't reply. 

** What do we look for in a Personal Statement?


- *Motivation*
- *Research Potential*:  don't tell, show !
- *Fit*


** Format/Style
- Keep it under 2 pages
-   


** Other things
*** Letter of Recommendation
*** CV
*** Choosing a school/professor
- Use CSRankings
*** Contact the professor (or not)
- Talking to the Prof (zoom, in person)


* Additional resources
-  http://www.pl-enthusiast.net/2022/10/03/how-to-write-a-grad-school-personal-statement/
-   http://www.pl-enthusiast.net/2022/10/03/how-to-write-a-grad-school-personal-statement/
