#+TITLE: Student Recruit
#+date: <2021-06-13 08:02>
#+description: recruit
#+filetags: blog students recruit
#+HTML_HEAD: <link rel="stylesheet" href="https://dynaroars.github.io/files/org.css">

a recruitment post for Vietnamese students 

Dear Prof. XYZ,

I am a faculty in the Computer Science Department at George Mason University in the Northern Virginia/Washington DC in the US. I am writing to you to get your help in encouraging students at YOURUNIV to apply to the CS graduate studies at George Mason. Briefly, GMU is the largest university in Virginia with about 38,000 students and also the top university in Virginia for CS research (ranked 36 in the US according to CSRankings). GMU CS has about 80 faculty with strong research in most of CS areas including Vision, Graphics, Robotics, Security, Data Mining, Databases, AI, ML, NLP, Software Engineering, HCI, Theory, Systems and Networks.  Our graduate students, both at Ph.D. and M.S. levels, are also very well-funded and supported by the department.  

I realize that many students from VN think doing a Ph.D. or MS. in the US is far-reached. But from my experience in reviewing CS applications for many years, I can assure that it is not — if they think they have a good chance in other countries, then they certainly do too at U.S universities. Vietnamese students, especially Ph.D.s, while being very few compared to other nationalities, typically have excellent reputation and work ethics—and that really attracts attentions from faculty. Indeed, one of the reasons I am writing this email is because my GMU colleagues said they think highly of Vietnamese students and explicitly ask me to help recruit more students from VN. In short, I hope that you can help me pass around words that many faculty that GMU specifically wants to work with good Vietnamese students and that you would help encourage your students to apply to GMU.

Note that GRE's are no longer required so hopefully that will take away some burden from the students. I also have several students from VN and we would be happy to answer and help prospective applicants.

Finally, in addition to student recruitment, I want to say hello and introduce myself to you, please reach out if you're in the DC area. I'd be happy to meet you and perhaps host your visit (e.g., giving talks or getting our department chairs and faculty to meet with you).

Here is the website for Ph.D. application: https://cs.gmu.edu/prospective-students/phd-program/. Also, feel free to connect your students with me, I would be happy to chat and answer their questions.  


ThanhVu Nguyen,  
